sudo: false
language: node_js
node_js:
  - "8.2.1"
env:
  global:
    - YARN_VERSION=0.27.5

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

script:
  - yarn run eslint

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      ./tasks/deploy.sh
    fi
  - |
    if [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      ./tasks/deploy-prod.sh
    fi

cache:
  yarn: true
  directories:
    - ~/.yarn
    - node_modules

notifications:
  email: evenchange4@gmail.com
