sudo: false
language: node_js
node_js:
  - 8.2.1
env:
  global:
    - YARN_VERSION=0.27.5

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

script:
  - yarn run eslint
  - yarn run test
  - yarn run pkg
  - ./tasks/zip.sh

after_success:
  - ./node_modules/.bin/codecov
  - |
    if [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      ./tasks/deploy.sh
    fi
  - |
    if [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      ./tasks/deploy-prod.sh
    fi

deploy:
  - provider: releases
    api_key:
      secure: os97UE+qeAitH5aeGF17JTWG3Vw33XijTXYfhve1Czp9Ia+J5rstW8C8/Z1C7HOlf4++Zfxz1bi4aIvAtpcJUCDeNJBRQw31yxJkXxBQu/lAHh9pT8B+8ikb5+G787eSCaXXISRMe/ctUZsKN8iHsEC/SCe+Mp0ly7OmotPZsFtelqR6JVxpxTADUsecvhJCPhQ607sTdfWXeUHBqe6zHRsN4t/oIJHi6ekB/ulTa4Fk/GyhIThK3ob0XdgKyc9/E4VshXXo/y9kXArld56y0znIkjnBxTq7/EcbXRAvPwzf4Nc2UIJlAJQWxW4kJ1PCwPJ1j/vEMOpkCcmjZ68yvaIv32O0DZB2we045OcmEKuWXP4kgrHXYBtF3UU64tlJKDMrOWW7wGuYF5sRW6pPad57S+dN+6Alk5TwjFY6F2rOK6YoTNQ9dB+SVvJOzEoEabmaULAoMze87U1c3sq3zpaBhJsc6i1FaWFzICKTgn8SQsNvmevMZil7wei4g0M0obE48bAQIK3BVX0XySfPAsEjaR8Tx/7EECm3Xgc0KUyHqgcpXSmmkSezOoW34SMFu4Ltcr9w4RCrxUoiuYATLJs4YOFCOoSOExaeD2RY/yh7yhr2JjjcgjSPQkdyUhF/LdYH5XkFQ+6AlxuY0ekL/SJQ0sZ7GATMv1LNzuXWIEM=
    file_glob: true
    skip_cleanup: true
    file: "./pkg/*"
    on:
      repo: evenchange4/micro-medium-api
      tags: true
  - provider: npm
    email: evenchange4@gmail.com
    api_key:
      secure: nzArSmu6hEZzCtvoUyqt0WC/NmSDg7v7ny4dPhIKfc0pbhborIh8KHN6zjww/yvplAtgncDBoj1s0E5GqoBFx/D08JeBuoiYoND/Xx2Hi2/ZF1Ikgq6YGlKnsr4J8+MBFS77z1vUVWMGfPGX3ZO8+uBKcJtPjYVQvb384IAiQZ5/oacf/LMLb0s/QeKWKZ88H7qoyDI9OUkYjzRukV4Rt0TRM+brgDMEuNEPZ3wM13V9j2nsDFNE6pBICiRYkq6YCr5C4L63tKxYFj+x6lpW7HmkebEmJcBSjvEELCsrzs7nbk0cT9lueb++FqE33uFLBJZKUJePhbRqTnQTTxyupG2avVu1+v2sU6kP6MMleT6f3HHkjutWnB4/9HNv8Doy7dp6SdOhU8iWka2/wq6l/pCyfFFbx7lANa7uiCSxNaN25XYnLXceHO87MVBH+EI1rv76qyqxI0EHyEul8ZgnuPJ2OX6630IlKfuUiUTzH4OmWhkYwv1P2eJstcu5cwG0lu+5HAxz9RMBIKf27ExQJ09LjzWK5qI8amyI0tWcucV6+vZYQDipVRXHpQT8kWVmnvlSwBeJ2KD8zhMrkqTe3MYcvayB9O+1kZRLy1L7CG2FnzNgzUOTsT6/IK3EPaDDd3ydHr5mgWHqkWlx2Sk1/gEDRI/2X5urIdFj3saW5uA=
    on:
      repo: evenchange4/micro-medium-api
      tags: true

cache:
  yarn: true
  directories:
    - "~/.yarn"
    - node_modules

notifications:
  email: evenchange4@gmail.com
